<a href="https://colab.research.google.com/github/nhn09/Python-basics-for-machine-learning/blob/main/python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
type("hello")
first_name = 'Fariha'
Last_name = 'Rah in'
print(len(Last_name))

print("I am {}, my best friend is Muhtadi {}".format(first_name, Last_name))

6
I am Fariha, my best friend is Muhtadi Rah in


# Python data structures and Boolean


*   Boolean
*   logical operators
*   List
*   Comparison
*   Dictionary
*   Tuples
*   Sets



In [ ]:
print(Last_name.isalnum())
print(Last_name.isalpha())
print(Last_name.istitle())
print(Last_name.endswith('N'))

False
False
False
False


*The isalnum()* method returns True if all the characters are alphanumeric, meaning alphabet letter (a-z) and numbers (0-9).

Example of characters that are not alphanumeric: (space)!#%&? etc.


---
RAHIN = TRUE
RA HIN = FALSE




In [ ]:

my_list = list()
type(my_list)
my_list=['Chittagong', 'Dhaka', 100, [1,2,3]]
print(my_list)
print(len(my_list[3]))
my_list[3].append("Vallagche")
print(my_list)

my_list[:] #all [ koi theke shuru tar index: ja chai tar cheye ek beshi likhbo ekhane]
my_list[1:3]

#insert vs append
# append() takes exactly one argument. more than one dile 
#it should be another list jeta eikhane kora hoise. 
#so eventually creates nested list.

my_list.append(['hehe', 'lala'])
my_list[:]



['Chittagong', 'Dhaka', 100, [1, 2, 3]]
3
['Chittagong', 'Dhaka', 100, [1, 2, 3, 'Vallagche']]


['Chittagong', 'Dhaka', 100, [1, 2, 3, 'Vallagche'], ['hehe', 'lala']]

Negative indexing means start from the end

-1 refers to the last item, -2 refers to the second last item etc.

In [ ]:
print(my_list[-1])


['hehe', 'lala']


This example returns the items from 100 (-4) to, but NOT including "['hehe', 'lala']" (-1):

In [ ]:
print(my_list[-4:-1])

['Dhaka', 100, [1, 2, 3, 'Vallagche']]


Now for insert, argument hoi erokom
list.insert(kon position e insert kora hobe, ki insert kora hobe)

In [ ]:
my_list.insert(3, "vum")
my_list[:]

['Chittagong', 'Dhaka', 100, 'vum', [1, 2, 3, 'Vallagche'], ['hehe', 'lala']]

In [ ]:
Number= [1,2,3,4,5]


Check if exists:

In [ ]:
if 100 in my_list:
  print("Yes , 100 is present.")

Yes , 100 is present.


To overcome the short comings of append, we can use extend.

In [ ]:
my_list.extend(['you', 'me'])
my_list[:]

['Chittagong',
 'Dhaka',
 100,
 'vum',
 [1, 2, 3, 'Vallagche'],
 ['hehe', 'lala'],
 'you',
 'me']

In [ ]:
sum(Number)


15

In [ ]:
Number.pop(3)
sum(Number)

11

Count: frequency count of an element

In [ ]:
my_list.count(['hehe','lala'])
my_list.count("you")

1

Set is unordered+ *No Duplicate*
<br>it's actually a hash table 
<br> No indexing <p> hehe</p>

In [ ]:
my_set= set()

my_set= {"Avengers","Ironman","AntMan","Avengers"}

print(my_set)

{'Avengers', 'Ironman', 'AntMan'}


In [ ]:
my_set.add("Hulk")
print(my_set)

{'Avengers', 'Ironman', 'AntMan', 'Hulk'}


In [ ]:
my_set2 = {"Hulk", "Bulk","Mulk"}
print(my_set2)

{'Hulk', 'Bulk', 'Mulk'}


In [ ]:
my_interset=my_set.intersection(my_set2)
print(my_interset)

{'Hulk'}


In [ ]:
my_set.difference(my_set2)

{'AntMan', 'Avengers', 'Ironman'}

In [ ]:
my_set.difference_update(my_set2)


In [ ]:
print(my_set)

{'Avengers', 'Ironman', 'AntMan'}


# Dictionary : Key value pairs

---



In [ ]:
dict_one= {"My father":"Teacher", "My mom": "Alrounder"}
print (dict_one)

{'My father': 'Teacher', 'My mom': 'Alrounder'}


In [ ]:
for x in dict_one:
    print (x)

for x in dict_one:
    print (dict_one[x])

for x in dict_one.items():
    print (x)

My father
My mom
Teacher
Alrounder
('My father', 'Teacher')
('My mom', 'Alrounder')


In [ ]:
car1_model = {"Marcedes": 1930}
car2_model = {"Audi": 1230}
car3_model = {"Masdhsk": 4530}

In [ ]:
car_type = { 'car_type1':car1_model,'car_type2':car2_model,'car_type3':car3_model}

In [ ]:
print(car_type)

{'car_type1': {'Marcedes': 1930}, 'car_type2': {'Audi': 1230}, 'car_type3': {'Masdhsk': 4530}}


In [ ]:
print(car_type['car_type1']['Marcedes'])

1930


# Tuple


---

unmutable ,  elements can't be changed after creation.


In [ ]:
my_tuple = ('Nohan','Loves','Tree')
print(my_tuple)

('Nohan', 'Loves', 'Tree')


TypeError: ignored

Numpy and inbuilt functions


In [ ]:
import numpy as np
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.shape

(5,)

# Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)

Keith Galli


# New Section

In [ ]:
a = np.array([[1,2,3]])
print(a)
a.shape

[[1 2 3]]


(1, 3)

In [ ]:
c = np.array([1,2,3])
print(c)
c.shape

[1 2 3]


(3,)

In [ ]:
b= np.array([[1,2,0],[1,3,2]])


#get dimension

b.ndim

2

In [ ]:
#get shape
b.shape

(2, 3)

In [ ]:
#datatye
print(b.dtype)
print(a.dtype)
print(c.dtype)

int64
int64
int64


Why int64? why not int32?

In [ ]:
#we can impose data type though

d = np.array([1,2,3], dtype='int16')
print(d.dtype)

int16


**Accessing / changing specific elements, rows, columns etc**


In [ ]:
arr_a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr_a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#get specific element  [row, col]

arr_a[1,4]

12

In [ ]:
#get specific row

arr_a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
#specific column 
arr_a[:, 3]

array([ 4, 11])

In [ ]:
#customizing output
# [row,start column:end column(exclusive):step size]
arr_a[0, 2:6:2] 
# 1 step gele 3 er por 4, 2 steps gele 5
# we can use -1 instead of 6 : arr_a[0, 2:-1:2]

array([3, 5])

In [ ]:
arr_a[1,4] = 15
print(arr_a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 15 13 14]]


In [ ]:
#change all the elements

arr_a[:,2:5:2]=0

In [ ]:
print(arr_a)

[[ 1  2  0  4  0  6  7]
 [ 8  9  0 11  0 13 14]]


In [ ]:
td_array = np.array([[[1,2],[2,3]],[[3,2],[4,5]]])
print(td_array)

[[[1 2]
  [2 3]]

 [[3 2]
  [4 5]]]


In [ ]:
td_array[:,0,0]

array([1, 3])

In [ ]:
td_array[0,:,1]=[5,5]

In [ ]:
print(td_array)

[[[1 5]
  [2 5]]

 [[3 2]
  [4 5]]]


Initialize different types of array

In [ ]:
#all 0's
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(((5,3,4)))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#any other number

fill_array=np.full((2,4,3), 10)

In [ ]:
# prebuilt array fill

np.full(fill_array.shape , 5)


array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [ ]:
#or

np.full_like(fill_array,2)

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [ ]:
#random decimal numbers

np.random.rand(3,4,3)

array([[[0.57344686, 0.84729537, 0.50937568],
        [0.22853389, 0.89990061, 0.5258612 ],
        [0.52781003, 0.39706516, 0.36261207],
        [0.9510356 , 0.02476657, 0.55524966]],

       [[0.4419968 , 0.74515187, 0.97776979],
        [0.99089775, 0.74218628, 0.8838686 ],
        [0.92739299, 0.44679355, 0.21534921],
        [0.00966356, 0.62471697, 0.56605893]],

       [[0.02350806, 0.21103895, 0.38506809],
        [0.0667469 , 0.01128374, 0.46169967],
        [0.98383251, 0.41914297, 0.93524437],
        [0.30551119, 0.04300281, 0.37185679]]])

In [ ]:
#random integer

np.random.randint(5,9, size=(3,2,4))

# 9 exlusive

array([[[8, 6, 8, 5],
        [8, 7, 5, 8]],

       [[7, 8, 6, 8],
        [5, 5, 5, 7]],

       [[5, 7, 6, 5],
        [7, 5, 5, 8]]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
build_practice = np.ones((5,5))
build_practice[1:4:2,1:4]=0
build_practice[2,1:4]=[0,9,0]
print(build_practice)


# **Beware of matrix copy!!!**

In [ ]:
copy_arr = np.random.randint(1,5,size=(2,3,4))
print(copy_arr)
paste_arr = copy_arr
paste_arr[1,1,1]=10
print(copy_arr)
print(paste_arr)

#the source is also changed which is unexpected

[[[3 4 2 3]
  [1 1 1 4]
  [4 3 2 2]]

 [[1 3 1 4]
  [4 3 2 1]
  [4 2 2 2]]]
[[[ 3  4  2  3]
  [ 1  1  1  4]
  [ 4  3  2  2]]

 [[ 1  3  1  4]
  [ 4 10  2  1]
  [ 4  2  2  2]]]
[[[ 3  4  2  3]
  [ 1  1  1  4]
  [ 4  3  2  2]]

 [[ 1  3  1  4]
  [ 4 10  2  1]
  [ 4  2  2  2]]]


In [ ]:
#to prevent 
copy_arr = np.random.randint(1,5,size=(1,2))
print(copy_arr)
paste_arr = copy_arr.copy()
paste_arr[0,1]=10
print(copy_arr)
print(paste_arr)


[[1 3]]
[[1 3]]
[[ 1 10]]


In [ ]:
np.sin(paste_arr)

array([[ 0.84147098, -0.54402111]])

# **Linear algebra**



In [ ]:
a= np.ones((3,3))
b =np.random.randint(1,5, size= (3,3))
print(a)
print(b)
c = np.matmul(a,b)
np.linalg.det(c)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 4 3]
 [2 1 2]
 [4 2 4]]


0.0